### PR TITLE
index: all

### PR DESCRIPTION
**Pull request by ESPNMichaelKidd**
adds functionality to iterate over all variant streams

### CODE REVIEW

**Comment by hassy** [comment]
Thanks @ESPNMichaelKidd. Looks good to me!

**Comment by hassy** [comment]
@ESPNMichaelKidd is there anything else you'd like to add to the PR or shall l go ahead and merge it?

**Comment by ESPNMichaelKidd** [comment]
@hassy I absolutely forgot to remove the draft from the title.  If you're happy with it, I'm happy with it.  Thanks for accepting this addition

**Comment by hassy** [comment]
Great, thanks for the PR @ESPNMichaelKidd!

**Pull request merged**
